### ISSUE TITLE
any usage of this lib?

### ISSUE THREAD

**Issue by benoitc** [ianopolous/merkle-btree#1]
I found your lib interresting. Doo you know bout any usage of it in prod?

**Comment by ianopolous** [comment]
We used it a lot in [Peergos](github.com/peergos/peergos), though we switched a few months ago to using a merkle CHAMP (Compressed hash array mapped trie) -

https://github.com/Peergos/Peergos/blob/master/src/peergos/shared/hamt/Champ.java

**Comment by benoitc** [comment]
@ianopolous thanks for the answer! Looking at peergos and new implementation :)

**Comment by ianopolous** [comment]
Note that it's all async in Peergos because of a constraint we have with cross compiling to JS (where CompletableFutures become Promises)

**Comment by benoitc** [comment]
i may port to erlang. I will let you know :)

**Comment by ianopolous** [comment]
Cool!
